project:
  type: website

website:
  title: "Diabetes Predictor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Diabetes Analysis
        menu:
          - text: "Static Analysis"
            href: analysis.qmd
          - text: "Shiny App"
            href: shiny-app.qmd
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    embed-resources: false

    